### ISSUE TITLE
Interceptions counted as completions?

### ISSUE THREAD

**Issue by nalin** [mrcaseb/nflfastR#147] opened 2020-12-13 01:04 UTC
I've noticed that any interception is also counted as a completion. While maybe technically valid this isn't how the NFL keep stats and was curious if this was intentional or an oversight.

For example when using the following for selecting all passes for the Buffalo Bills and grouping by passers:
```
data %>%
filter(posteam=="BUF", sack==0, play_type=="pass", down>=1) %>% 
group_by(passer) %>% 
summarize(completions=n()-sum(incomplete_pass))
```
You see the result is Josh Allen with 307 completions when in reality he has 299:
```
# A tibble: 4 x 2
  passer     completions
  <chr>            <dbl>
1 C.Beasley            1
2 I.McKenzie           1
3 J.Allen            307
4 M.Barkley            3
```

If we subtract the interceptions we get the right number.

**Comment by TheMathNinja** [comment] 2020-12-13 13:57
Are you sure the issue here isn't that you haven't filtered out completions that were called back due to penalty? I would be pretty shocked if INTs were being counted as completions.

**Comment by guga31bb** [comment] 2020-12-13 14:39
```
pbp <- readRDS(url("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds"))
pbp %>%
  filter(posteam=="BUF", complete_pass == 1, interception == 1) %>%
  nrow()
[1] 0
```
I cannot reproduce this so am closing but please comment if you do find a bug.

**Closed by guga31bb** 2020-12-13 14:39 UTC

**Comment by nalin** [comment] 2020-12-13 20:09
Looks complete_pass is accurate. However, fact remains that total passes minus incomplete_passes still includes interceptions. maybe that's by design. Thanks for responding quickly to this.

**Comment by nalin** [comment] 2020-12-13 20:15
> Are you sure the issue here isn't that you haven't filtered out completions that were called back due to penalty? I would be pretty shocked if INTs were being counted as completions.

Yes. play_type='pass' excludes plays called back by penalty which have play_type='no_play'

**Comment by TheMathNinja** [comment] 2020-12-13 20:25
Yes, Pass Attempts = Complete Passes + Incomplete Passes + Interceptions. This is the definition of pass attempts. Seems like you subtracted "Incomplete Passes" from each side and expected Completions.

**Comment by mrcaseb** [comment] 2020-12-13 20:25
The `play_type` variable has been inherited from nflscrapR. 

`play_type = "pass"` includes a lot of different pass plays (see screenshot)

![image](https://user-images.githubusercontent.com/38586519/102022812-879d9f00-3d89-11eb-8737-de90c227acb7.jpeg)

That's the reason why there are additional variables like `complete_pass` or `incomplete_pass`.
