### ISSUE TITLE
Progress Bar Always Says 100%

### ISSUE THREAD

**Issue by z-feldman** [mrcaseb/nflfastR#9] opened 2020-05-04 18:44 UTC
Just started scraping play_by_play data with fast_scraper() and the progress bar grows correctly but it always says "100%" at the end

**Comment by mrcaseb** [comment] 2020-05-04 18:49
Do you mean something like this?
<img width="760" alt="Bildschirmfoto 2020-05-04 um 20 47 29" src="https://user-images.githubusercontent.com/38586519/81001893-ae394600-8e48-11ea-805e-d9c8bf5c51b4.png">

Progress Bar <50% but 100% on the right?

**Comment by z-feldman** [comment] 2020-05-04 18:51
Yea

**Comment by mrcaseb** [comment] 2020-05-04 18:52
Okay. This is the intended behaviour of `furrr`. Think of the 100% like its the goal, not the current value. 
I'll close this because we can't manipulate `furrr` anyway

**Closed by mrcaseb** 2020-05-04 18:52 UTC

**Comment by z-feldman** [comment] 2020-05-04 19:00
ohhhhh, makes sense
