### ISSUE TITLE
New end_yardline_100 variable

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#54] opened 2020-07-19 17:45 UTC
I'm wondering if you could add a new variable called end_yardline_100 to the data set. Similar to end_yard_line but using the numeric format line yardline_100. In particular, I think this variable could be extremely helpful for catching any errors in missed yards on a play (e.g. making sure that the yards gained/lost on the play actually matches up to the difference between end_yardline_100 and yardline_100). One implication here is that end_yardline_100 should be 0 on touchdown and 2 point conversion plays (currently I know end_yard_line is NA on touchdowns and 2 point conversions) and 100 on safeties (currently end_yard_line is NA on safeties).

I also think it would be most helpful to define this variable as the yard line which is/would-be where the ball is placed for the next play from scrimmage. I'm not sure whether or not this is the way end_yard_line is defined right now.

For example:  2161 | 2019_01_BUF_NYJ is a missed field goal where the ball was snapped at the BUF 27 and held at the BUF 35. The ball is placed for the next play at the BUF 35 but end_yard_line is BUF 27 here. Is this a bug/error or is this how you are hoping to define this variable currently? (I'm assuming bug but not sure).
Similarly, 1159 | 2019_01_BUF_NYJ is a punt which is snapped at the BUF 40 but goes to NYJ end zone for a touchback. the next play is from the NYJ 20, but end_yard_line on this play is BUF 40, not NYJ 20.

**Comment by guga31bb** [comment] 2020-08-17 14:29
> For example: 2161 | 2019_01_BUF_NYJ is a missed field goal where the ball was snapped at the BUF 27 and held at the BUF 35. The ball is placed for the next play at the BUF 35 but end_yard_line is BUF 27 here. Is this a bug/error or is this how you are hoping to define this variable currently? (I'm assuming bug but not sure).
> Similarly, 1159 | 2019_01_BUF_NYJ is a punt which is snapped at the BUF 40 but goes to NYJ end zone for a touchback. the next play is from the NYJ 20, but end_yard_line on this play is BUF 40, not NYJ 20.

Just checked and these are incorrect in the data provided by NFL. 
![image](https://user-images.githubusercontent.com/1425357/90407249-46fc7600-e074-11ea-9157-5bf46e476a2d.png)

Closing this as it's not a bug on our end and a fixed end yard line could be derived from using `dplyr::lead(yardline_100)` (or 100 minus that on plays where possession changed).

**Closed by guga31bb** 2020-08-17 14:29 UTC
Labels: NFL data issue
