### ISSUE TITLE
Some plays have incorrectly have NA posteam and play_type

### ISSUE THREAD

**Issue by nalin** [mrcaseb/nflfastR#151] opened 2020-12-19 02:49 UTC
`
data %>%
  filter(season==2020, down>=1, is.na(play_type), is.na(posteam)) %>%
  view()
` 
You'll see 41 plays that should have a valid posteam and play_type (even if it's no_play) but both attributes are NA.

**Comment by guga31bb** [comment] 2020-12-19 15:52
Duplicate of #44 (missing info when there are offsetting penalties)

**Closed by guga31bb** 2020-12-19 15:52 UTC
