### ISSUE TITLE
Curious occurrences of N/A EPA

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#22] opened 2020-06-21 20:10 UTC
I'm not quite sure why these plays have "NA" for epa variable:

game_id 2017_03_CIN_GB
play_id 1149 and 1173

game_id 2015_14_PIT_CIN
play_id 2089

**Comment by guga31bb** [comment] 2020-06-21 22:23
Thanks! This appears to be yet another issue caused by NFL providing plays out of order:
``` r
  quarter_seconds_remai~ desc                                                           ep     epa
                   <dbl> <chr>                                                       <dbl>   <dbl>
1                    900 9-C.Boswell kicks 65 yards from PIT 35 to end zone, Touch~  0.973  0     
2                    900 (15:00) (Shotgun) 5-A.McCarron pass short right to 32-J.H~  0.973 NA     
3                    850 9-C.Boswell extra point is GOOD, Center-60-G.Warren, Hold~  0.931  0.0685
4                    850 (14:10) (Shotgun) 5-A.McCarron pass short left intended f~ NA     NA     
5                    850 9-C.Boswell kicks 75 yards from PIT 20 to CIN 5. 19-B.Tat~  0.973  0.900
```

**Comment by guga31bb** [comment] 2020-06-22 16:15
This was caused by NFL not providing `drive` on the PAT following defensive TDs and has been fixed. Thanks for catching all of these! Finally starting the re-scrape and then the data will reflect all these updates

**Comment by guga31bb** [comment] 2020-06-22 17:19
Ok data in the data repo have been updated- please let us know if anything else doesn't look right!

**Comment by TheMathNinja** [comment] 2020-06-22 18:51
I think something went wrong with the re-scrape. All of a sudden, my fumble and interception coefficients for EPA are somewhat negligible (i.e. -0.5 instead -3).

**Comment by guga31bb** [comment] 2020-06-22 18:55
Yep you're right. Sigh.

**Comment by guga31bb** [comment] 2020-06-22 19:20
Was a bug induced by putting the plays in the right order. Re-scraping now...

**Comment by guga31bb** [comment] 2020-06-22 20:26
Ok it is hopefully fixed now, please let us know how it looks!

**Comment by TheMathNinja** [comment] 2020-06-24 11:44
Looks great!

**Closed** 2020-06-24 17:13 UTC
