### ISSUE TITLE
Inconsistent yardage on lateral plays

### ISSUE THREAD

**Issue by waitwhereami** [mrcaseb/nflfastR#143] opened 2020-11-23 20:12 UTC
There seems to be some inconsistency with how **yards_gained** is calculated on lateral plays. If the total yardage from the play is positive, **yards_gained** has the correct value, however, if the yardage from the play is negative, **yards_gained** is always 0. Additionally, there seem to be some issues with the **air_yards** and **yards_after_catch** fields on these plays as well, but that appears to be less consistent; they just don't seem to add up correctly at all unless I'm missing something.

Examples:
play_id | game_id | desc | yards_gained | air_yards | yards_after_catch
------------ | ------------- | -------------------------------- | -------- | ----------------- | ----------
1439 | 2020_03_DAL_SEA | (12:52) (Shotgun)   4-D.Prescott pass short middle to 20-T.Pollard to DAL 15 for -6 yards.   Lateral to 88-C.Lamb to DAL 16 for 1 yard (97-P.Ford). | 0 (exp: -5) | -3 | -2
1909 | 2020_06_LA_SF | (1:26) (Shotgun) 16-J.Goff pass short right to 10-C.Kupp to LA 23 for -5 yards. Lateral to 27-D.Henderson pushed ob at LA 32 for 9 yards (20-J.Ward). | 4 (exp: 4) | -3 | 3
1334 | 2020_07_CLE_CIN | (10:26) (Shotgun) 6-B.Mayfield pass short middle to 80-J.Landry to CLE 47 for -6 yards. Lateral to 27-K.Hunt to 50 for 3 yards (21-M.Alexander; 90-K.Kareem). | 0 (exp: -3) | -4 | 1
2762 | 2020_08_ATL_CAR | (3:57) (Shotgun) 6-P.Walker pass short middle to 10-C.Samuel to ATL 31 for -7 yards. Lateral to 11-R.Anderson to ATL 21 for 10 yards (26-I.Oliver). | 3 (exp: 3) | -3 | 3

**Comment by guga31bb** [comment] 2020-11-23 20:30
Duplicate of https://github.com/mrcaseb/nflfastR/issues/115

**Comment by guga31bb** [comment] 2020-12-13 17:52
Closing since it's a duplicate

**Closed by guga31bb** 2020-12-13 17:52 UTC
