### ISSUE TITLE
Duplicate Unique Identifier (game_id, play_id, drive) combinations

### ISSUE THREAD

**Issue by nateb7722** [mrcaseb/nflfastR#155] opened 2020-12-23 04:40 UTC
I noticed that there are some duplicated unique Identifiers using game ID, play ID, and drive number combinations. Some examples are:
1) Game ID: 2000_03_PIT_CLE, play ID: 2767, drive: 18
2) Game ID: 2000_03_PIT_CLE, play ID: 2768, drive: 18
3) Game ID: 2000_06_WAS_PHI, play ID: 1825, drive: 12
4) Game ID: 2000_11_OAK_DEN, play ID: 2323, drive: 15
5) Game ID: 2002_05_KC_NYJ, play ID: 1020, drive: 8

**Comment by guga31bb** [comment] 2020-12-23 13:52
Duplicate of #33 . 

https://github.com/mrcaseb/nflfastR/issues/33#issuecomment-655366270

**Closed by guga31bb** 2020-12-23 13:52 UTC
